---
- name: Install and Configure Grafana
  hosts: all
  become: yes  # Run as sudo
  vars:
    grafana_version: latest
    http_port: 3000
    domain: localhost
    admin_user: admin
    admin_password: admin

  tasks:
    - name: Install dependencies
      apt:
        name: software-properties-common
        state: present

    - name: Add Grafana GPG Key
      get_url:
        url: https://packages.grafana.com/gpg.key
        dest: /usr/share/keyrings/grafana.gpg

    - name: Add Grafana Repository
      lineinfile:
        path: /etc/apt/sources.list.d/grafana.list
        line: "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main"
        create: yes

    - name: Update Package Lists
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start and Enable Grafana Service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Wait for Grafana to Start
      pause:
        seconds: 10

    - name: Verify Grafana is Running
      uri:
        url: "http://localhost:{{ http_port }}"
        status_code: 200
      ignore_errors: yes
