---
- name: Install and Configure Apache Tomcat
  hosts: all
  become: yes  # Run tasks as sudo

  vars:
    tomcat_version: "10.1.18"  # Change to the required version
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    install_dir: "/opt/tomcat"
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

  tasks:
    - name: Install required dependencies (Java)
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Create Tomcat user and group
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        createhome: no

    - name: Download Apache Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Create installation directory
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0755'

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Set permissions for Tomcat directory
      file:
        path: "{{ install_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Create systemd service file for Tomcat
      copy:
        dest: "/etc/systemd/system/tomcat.service"
        content: |
          [Unit]
          Description=Apache Tomcat Server
          After=network.target

          [Service]
          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          Type=forking
          Environment=CATALINA_HOME={{ install_dir }}
          Environment=CATALINA_BASE={{ install_dir }}
          ExecStart={{ install_dir }}/bin/startup.sh
          ExecStop={{ install_dir }}/bin/shutdown.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: started

    - name: Verify Tomcat is running
      uri:
        url: "http://localhost:8080"
        status_code: 200
      ignore_errors: yes
