---
- name: Install Grafana on Ubuntu
  hosts: grafana_servers
  become: yes
  tasks:

    - name: Install required dependencies
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - wget
        state: present
        update_cache: yes

    - name: Add Grafana GPG key
      ansible.builtin.get_url:
        url: https://packages.grafana.com/gpg.key
        dest: /usr/share/keyrings/grafana.key
        mode: '0644'

    - name: Add Grafana APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started
