- name: Install and Configure Apache Tomcat
  hosts: all
  become: yes  # Run as sudo

  vars:
    tomcat_version: "10.1.18"
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    install_dir: "/opt/tomcat"
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

  tasks:
    - name: Install required dependencies (Java)
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        createhome: no
        system: yes
